### ISSUE TITLE
The concept for this list is gamified systems, not gamification

### ISSUE THREAD

**Issue by notnsane** [vinkla/awesome-edutainment#2]
Sorry for being "that guy" but I finished a couple courses on gamification and serious games and I have to point out a small correction (I might be wrong on the approach to this, though, so just correct me if I'm wrong): what I'm reading on the awesome list are **gamified learning systems**, more akin to **edutainment** software, not **gamification** (as a concept) per se.
Gamification (as a list of resources) should point out to research papers/books like [this one](http://www.gamified.uk/even-ninja-monkeys-like-to-play/) or specific tools for developing gamified systems.

I feel like a "gamification" list should point towards papers, tools and research; much like a "marketing" list should point towards marketing papers, tools and research and not end-user software that are products of such marketing systems.

Whether this list name should be changed to "gamified-learning-systems-awesome" or similar, no idea, but at least I was pretty confused when I looked at this list at first.

(I'll add a small pull request to contribute something at least, besides the rant =P)

**Comment by vinkla** [comment]
IMO it is good to be "that guy or girl". Otherwise we wouldn't learn from each other.

This actually came up last week while I was discussing "gamification" with a college. I showed her the list and she told me this isn't per say "gamification". It is similar to "gamification" but maybe there is another word.

I agree that we should find another name for the list instead. Any suggestions?

Thanks for pointing it out btw!

**Comment by vinkla** [comment]
@notnsane maybe we could rename the repository to **edutainment** as you have written above. What do you think about that?

**Comment by vinkla** [comment]
Fixed.

**Comment by notnsane** [comment]
Hey @vinkla! Sorry I couldn't reply earlier, I couldn't find a solution to the problem and I didn't want to post "well, no idea".
A couple days ago came with a somewhat decent solution and then I forgot to post here (I was walking outside and have no internet)

I think your approach is clear enough, my suggestion is "learning websites", though the scope might be too wide - not sure if including MOOCs goes outside the idea of this list.

Thanks again for creating it!
